### ISSUE TITLE
Add support for FunctionUrls

### ISSUE THREAD

**Issue by AramMessdaghi9001** [micronaut-projects/micronaut-aws#1352]
### Feature description

AWS now supports [Function URLs](https://docs.aws.amazon.com/lambda/latest/dg/lambda-urls.html) which do not seem to work ootb with the default Micronaut Lambda Proxy Handler

**Comment by msailes** [comment]
Can you post the error you get?

**Comment by AramMessdaghi9001** [comment]
```
{"message":"Method Not Allowed","_links":{"self":{"href":"https://ek26l3ovpjexnpf7hkmvuyrkte0qegft.execute-api.eu-central-1.amazonaws.comnull","templated":false}},"_embedded":{"errors":[{"message":"Method [GET] not allowed for URI [https://ek26l3ovpjexnpf7hkmvuyrkte0qegft.execute-api.eu-central-1.amazonaws.comnull]. Allowed methods: [POST]"}]}}
```

**Comment by sdelamo** [comment]
You can now generate a Micronaut Serverless function with Function URL, CDK and Lambda: 

https://micronaut.io/launch?type=FUNCTION&name=demo&package=com.example&javaVersion=JDK_11&lang=JAVA&build=GRADLE&test=JUNIT&features=aws-lambda-function-url&features=aws-lambda&features=aws-cdk&version=3.6.1

if you want to use application type `Application` , then you should use Payload version 1.0. Because `micronaut-function-aws-api-proxy` supports only [Payload format version 1.0](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.proxy-format).
